### ISSUE TITLE
stop: Error while Killing

### ISSUE THREAD

**Issue by jajajaime** [nicoschi/mutagen-for-docksal#13]
I am seeing the following error:
```
% fin mutagen stop
Disconnecting project network...
Stopping services...
[+] Running 4/4
 ⠿ Container myproject_web_1            Stopped                                                      1.1s
 ⠿ Container myproject_elasticsearch_1  Stop...                                                      0.7s
 ⠿ Container myproject_db_1             Stopped                                                      1.0s
 ⠿ Container myproject_cli_1            Stopped                                                      0.1s
[+] Running 0/0
 ⠿ Container myproject_cli_1  Error while Killing                                                    0.0s
Error response from daemon: Cannot kill container: befc96a1ebbc70ec050e39a3b666657bce9ed7edf20006979457863caa64c546: Container befc96a1ebbc70ec050e39a3b666657bce9ed7edf20006979457863caa64c546 is not running
```
This happens on any project that I stop, and every time.

I am running the `develop` version of Docksal, as well as the latest Docker Desktop for Apple Silicon.

----

My guess is that the new Docker just doesn't allow for `fin rm cli` to run when the container is stopped/exited.
`docker rm <container-name>` seems to do the trick.

**Comment by CyberJack** [comment]
This project is only a wrapper around the `fin` command to start/stop a mutagen project before/after executing a `fin` command. 

When you start a project it will start your Docksal project first, and when it's running, a mutagen project will be started. If you stop your project, the mutagen project will be stopped first, after which the Docksal project is stopped.

The error you see comes from the `fin` command and not from this wrapper, so it's best to report this in the [docksal repository](https://github.com/docksal/docksal), especially since you are running the development version of Docksal.

**Comment by nicoschi** [comment]
I can confirm this problem exists for new versions of Docksal, because containers cannot be removed after docksal project is stopped. 

I will release a new version which will just invert the order of actions executed on fin mutagen stop removing cli container first of all and then stopping docksal project.
